#!/usr/bin/bash

CC= g++

CFLAGS="-Wall -Wextra -O2"

SRC="Main.cpp"

LINK= "./Include/LibTypes.o ./Include/file_handle.o  Tokenizer.cpp Parser.cpp"

OBJ="Parser.o Tokenizer.o  ./Include/LibTypes.o ./Include/file_handle.o"

EXE="Ara"




cmd $CC $CFLAGS -c Parser.cpp
cmd $CC $CFLAGS -c Tokenizer.cpp
cmd $CC $CFLAGS $OBJ -o $EXE $SRC
